version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - docker-mysql.env
    volumes:
      # Initialize a database on startup
      - ./product.sql:/docker-entrypoint-initdb.d/product.sql
      - product-data:/var/lib/mysql
    ports:
      - 3308:3306

# To interact with the MySQL console from external:
# mysql -P [host port] --protocol=tcp -u [mysql user] -p
# example: mysql -P 3308 --protocol=tcp -u admin -p

volumes:
  product-data:

