version: '3.8'

services:
  db:
    image: mysql:8.0.29
    container_name: mysql_ctr
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secretpassword
      MYSQL_ROOT_PASSWORD: example
      MySQL_DATABASE: product
    ports:
     - 3306:3306
    # Initialize a database when container is spun up
    volumes:
     - ./product.sql:/docker-entrypoint-initdb.d/product.sql
